### ISSUE TITLE
Bulk add button did not work

### ISSUE THREAD

**Issue by jim-sheldon** [globaldothealth/turnkey-curator-portal#75]
@julianasopko could you add steps to reproduce?

**Comment by julianasopko** [comment]
when you click Create New > New Bulk Upload nothing happens

**Comment by stanislaw-zakrzewski** [comment]
Update no.1
This issue is related to the Junior Curator role. While Senior Curators are able to create new bulk uploads Junior Curators are not allowed by the system, but they can still see the button for adding a new bulk upload.

Furthermore the cases added by the Curator using bulk add are not verified.

The solution to this is to allow Junior Curators to add new bulk cases, but mark them as not verifed. And mark cases added by Senior Curator as verified. Working on this right now.
